routes/admin.php
<?php
/*------ Auth ------*/
Route::prefix("auth")->name("authAdmin.")->group(function (){
    $controller = "AuthController@";
    Route::get("/login", $controller . "login")->name("login");
    Route::post("/authenticate", $controller . "postLogin")->name("postLogin");
    Route::get("/logout", $controller . "logout")->name("logout");
});

/*------ Admin ------*/
Route::namespace("Admin")->prefix("admin")->middleware('auth')->name("admin.")->group(function (){

        /*------ Q&A Routes ------*/
        $prefix = "qa";
        $controller = "qa";
        Route::prefix($prefix)->name($controller . ".")->group(function () use($controller){
            $controllerName = ucfirst($controller) . "Controller@";
            Route::get("/", $controllerName . "index")->middleware("can:" . $controller . ".index")->name("index");
            Route::get("create", $controllerName . "create")->middleware("can:" . $controller . ".create")->name("create");
            Route::post("store", $controllerName . "store")->middleware("can:" . $controller . ".create")->name("store");
            Route::get("edit/{id}", $controllerName . "edit")->middleware("can:" . $controller . ".edit")->name("edit");
            Route::post("update/{id}", $controllerName . "update")->middleware("can:" . $controller . ".edit")->name("update");
            Route::get("delete/{id}", $controllerName . "delete")->middleware("can:" . $controller . ".delete")->name("delete");
        });

    /*------ Product Routes ------*/
    $prefix = "product";
    $controller = "product";
    Route::prefix($prefix)->name($controller . ".")->group(function () use($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get("/", $controllerName . "index")->middleware("can:" . $controller . ".index")->name("index");
        Route::get("create", $controllerName . "create")->middleware("can:" . $controller . ".create")->name("create");
        Route::post("store", $controllerName . "store")->middleware("can:" . $controller . ".create")->name("store");
        Route::get("edit/{id}", $controllerName . "edit")->middleware("can:" . $controller . ".edit")->name("edit");
        Route::post("update/{id}", $controllerName . "update")->middleware("can:" . $controller . ".edit")->name("update");
        Route::get("delete/{id}", $controllerName . "delete")->middleware("can:" . $controller . ".delete")->name("delete");
    });

    /*------ Product Category ------*/
    $prefix = "product_category";
    $controller = "product_category";
    Route::prefix($prefix)->name($controller . ".")->group(function () use($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get("/", $controllerName . "index")->middleware("can:" . $controller . ".index")->name("index");
        Route::get("create", $controllerName . "create")->middleware("can:" . $controller . ".create")->name("create");
        Route::post("store", $controllerName . "store")->middleware("can:" . $controller . ".create")->name("store");
        Route::get("edit/{id}", $controllerName . "edit")->middleware("can:" . $controller . ".edit")->name("edit");
        Route::post("update/{id}", $controllerName . "update")->middleware("can:" . $controller . ".edit")->name("update");
        Route::get("delete/{id}", $controllerName . "delete")->middleware("can:" . $controller . ".delete")->name("delete");
    });

    /*------ Product Tags ------*/
    $prefix = "product_tags";
    $controller = "product_tags";
    Route::prefix($prefix)->name($controller . ".")->group(function () use($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get("/", $controllerName . "index")->middleware("can:" . $controller . ".index")->name("index");
        Route::get("create", $controllerName . "create")->middleware("can:" . $controller . ".create")->name("create");
        Route::post("store", $controllerName . "store")->middleware("can:" . $controller . ".create")->name("store");
        Route::get("edit/{id}", $controllerName . "edit")->middleware("can:" . $controller . ".edit")->name("edit");
        Route::post("update/{id}", $controllerName . "update")->middleware("can:" . $controller . ".edit")->name("update");
        Route::get("delete/{id}", $controllerName . "delete")->middleware("can:" . $controller . ".delete")->name("delete");
    });

    /*------ Settings ------*/
    $prefix = "setting";
    $controller = "setting";
    Route::prefix($prefix)->name($controller . ".")->group(function () use($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get("/", $controllerName . "index")->middleware("can:" . $controller . ".index")->name("index");
        Route::get("create", $controllerName . "create")->middleware("can:" . $controller . ".create")->name("create");
        Route::post("store", $controllerName . "store")->middleware("can:" . $controller . ".create")->name("store");
        Route::get("edit/{id}", $controllerName . "edit")->middleware("can:" . $controller . ".edit")->name("edit");
        Route::post("update/{id}", $controllerName . "update")->middleware("can:" . $controller . ".edit")->name("update");
        Route::get("delete/{id}", $controllerName . "delete")->middleware("can:" . $controller . ".delete")->name("delete");
    });

    /*------ User ------*/
    $prefix = "user";
    $controller = "user";
    Route::prefix($prefix)->name($controller . ".")->group(function () use($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get("/", $controllerName . "index")->middleware("can:" . $controller . ".index")->name("index");
        Route::get("create", $controllerName . "create")->middleware("can:" . $controller . ".create")->name("create");
        Route::post("store", $controllerName . "store")->middleware("can:" . $controller . ".create")->name("store");
        Route::get("edit/{id}", $controllerName . "edit")->middleware("can:" . $controller . ".edit")->name("edit");
        Route::post("update/{id}", $controllerName . "update")->middleware("can:" . $controller . ".edit")->name("update");
        Route::get("delete/{id}", $controllerName . "delete")->middleware("can:" . $controller . ".delete")->name("delete");
    });

    /*------ Role ------*/
    $prefix = "role";
    $controller = "role";
    Route::prefix($prefix)->name($controller . ".")->group(function () use($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get("/", $controllerName . "index")->middleware("can:" . $controller . ".index")->name("index");
        Route::get("create", $controllerName . "create")->middleware("can:" . $controller . ".create")->name("create");
        Route::post("store", $controllerName . "store")->middleware("can:" . $controller . ".create")->name("store");
        Route::get("edit/{id}", $controllerName . "edit")->middleware("can:" . $controller . ".edit")->name("edit");
        Route::post("update/{id}", $controllerName . "update")->middleware("can:" . $controller . ".edit")->name("update");
        Route::get("delete/{id}", $controllerName . "delete")->middleware("can:" . $controller . ".delete")->name("delete");
    });

    /*------ Partner ------*/
    $prefix = "partner";
    $controller = "partner";
    Route::prefix($prefix)->name($controller . ".")->group(function () use($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get("/", $controllerName . "index")->middleware("can:" . $controller . ".index")->name("index");
        Route::get("create", $controllerName . "create")->middleware("can:" . $controller . ".create")->name("create");
        Route::post("store", $controllerName . "store")->middleware("can:" . $controller . ".create")->name("store");
        Route::get("edit/{id}", $controllerName . "edit")->middleware("can:" . $controller . ".edit")->name("edit");
        Route::post("update/{id}", $controllerName . "update")->middleware("can:" . $controller . ".edit")->name("update");
        Route::get("delete/{id}", $controllerName . "delete")->middleware("can:" . $controller . ".delete")->name("delete");
    });

    /*------ Menu ------*/
    $prefix = "menu";
    $controller = "menu";
    Route::prefix($prefix)->name($controller . ".")->group(function () use($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get("/", $controllerName . "index")->middleware("can:" . $controller . ".index")->name("index");
    });

    /*------ Blog ------*/
    $prefix = "blog";
    $controller = "blog";
    Route::prefix($prefix)->name($controller . ".")->group(function () use($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get("/", $controllerName . "index")->middleware("can:" . $controller . ".index")->name("index");
        Route::get("create", $controllerName . "create")->middleware("can:" . $controller . ".create")->name("create");
        Route::post("store", $controllerName . "store")->middleware("can:" . $controller . ".create")->name("store");
        Route::get("edit/{id}", $controllerName . "edit")->middleware("can:" . $controller . ".edit")->name("edit");
        Route::post("update/{id}", $controllerName . "update")->middleware("can:" . $controller . ".edit")->name("update");
        Route::get("delete/{id}", $controllerName . "delete")->middleware("can:" . $controller . ".delete")->name("delete");
    });

    /*------ Blog ------*/
    $prefix = "blog_category";
    $controller = "blog_category";
    Route::prefix($prefix)->name($controller . ".")->group(function () use($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get("/", $controllerName . "index")->middleware("can:" . $controller . ".index")->name("index");

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require("admin.php");

Route::namespace("EndUser")->group(function(){
    Route::get('/', 'PageController@index')->name('page.index');

    /*----- Authentication -----*/
    $prefix = "";
    $controller = "auth";
    Route::prefix($prefix)->name($controller . ".")->group(function () use ($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get("/dang-nhap", $controllerName . "login")->name("login");
        Route::post("/kiem-tra-dang-nhap", $controllerName . "checkLogin")->name("checkLogin");
        Route::get("dang-ky", $controllerName . "register")->name("register");
        Route::post("kiem-tra-dang-ky", $controllerName . "checkRegister")->name("checkRegister");
        Route::get("dang-xuat", $controllerName . "logout")->name("logout");
    });
    /*----- Cua Hang -----*/
    $prefix = "cua-hang";
    $controller = "shop";
    Route::prefix($prefix)->name($controller . ".")->group(function () use ($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get("/", $controllerName . "index")->name("index");
        Route::get("san-pham={slug}", $controllerName . "productDetail")->name("productDetail");
        Route::get("danh-muc={slug}", $controllerName . "showProductByCategory")->name("showProductByCategory");
        Route::get("tag={slug}", $controllerName . "showProductByTag")->name("showProductByTag");
        Route::get("tim-kiem", $controllerName . "searchBrand")->name("searchBrand");
        Route::get("thuong-hieu/{slug}", $controllerName . "showProductByBrand")->name("showProductByBrand");
    });

    /*----- Gio Hang -----*/
    $prefix = "gio-hang";
    $controller = "cart";
    Route::prefix($prefix)->name($controller . ".")->group(function () use ($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get('/', $controllerName . "showCart")->name("showCart");
        Route::get('them-san-pham/{id}', $controllerName . "addToCart")->name("addToCart");
        Route::get('them-gio-hang/{id}', $controllerName . "addCartForDetailProduct")->name("addCartForDetailProduct");
        Route::post('cap-nhat', $controllerName . "updateCart")->name("updateCart");
        Route::get('xoa-san-pham/{id}', $controllerName . "deleteProduct")->name("deleteProduct");
        Route::get('ap-dung-coupon', $controllerName . "applyCoupon")->name("applyCoupon");
    });

    /*----- WishList -----*/
    $prefix = "danh-sach-yeu-thich";
    $controller = "wishList";
    Route::prefix($prefix)->name($controller . ".")->group(function () use ($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get("them-danh-sach-yeu-thich/{id}", $controllerName."addWishList")->name("addWishList");
        Route::get("/", $controllerName."showWishList")->name("showWishList");
        Route::get("xoa-san-pham-yeu-thich", $controllerName."deleteWishProduct")->name("deleteWishProduct");
    });

    /*----- Thanh Toan -----*/
    $prefix = "thanh-toan";
    $controller = "checkout";
    Route::prefix($prefix)->name($controller . ".")->group(function () use ($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get('/', $controllerName."checkLoginToCheckOut")->name("checkLoginToCheckOut");
        Route::get('/huyen-thanh-pho/{id}', $controllerName."getDistrict")->name("getDistrict");
        Route::get('/xa-phuong/{id}', $controllerName."getWard")->name("getWard");
        Route::post('confirmCheckout', $controllerName."confirmCheckout")->name("confirmCheckout");
        Route::get('ghi-nhan-don-hang', $controllerName."checkoutSuccess")->name("checkoutSuccess");
    });

    /*----- Blog -----*/
    $prefix = "tin-tuc";
    $controller = "blog";
    Route::prefix($prefix)->name($controller . ".")->group(function () use ($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::get("/", $controllerName."index")->name("index");
        Route::get("danh-muc={slug}", $controllerName."blogByCategory")->name("blogByCategory");
        Route::get("/{slug}", $controllerName."blogDetail")->name("blogDetail");
    });

    /*----- Comment -----*/
    $prefix = "binh-luan";
    $controller = "comment";
    Route::prefix($prefix)->name($controller . ".")->group(function () use ($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::post("store/{slug}", $controllerName."store")->name("store");
        Route::post("store-reply", $controllerName."replyComment")->name("replyComment");
        Route::post("sua-binh-luan/{id}", $controllerName."editComment")->name("editComment");
        Route::get("xoa-binh-luan/{id}", $controllerName."deleteComment")->name("deleteComment");
    });

    /*----- Review -----*/
    $prefix = "danh-gia-san-pham";
    $controller = "review";
    Route::prefix($prefix)->name($controller . ".")->group(function () use ($controller){
        $controllerName = ucfirst($controller) . "Controller@";
        Route::post("{id}", $controllerName."storeReview")->name("storeReview");
        Route::post("sua-danh-gia/{id}", $controllerName."editReview")->name("editReview");
        Route::get("xoa-danh-gia/{id}", $controllerName."deleteReview")->name("deleteReview");
    });

});

resources/views/admin/partials/footer.blade.php
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; Your Website 2020</div>
            <div>
                <a href="#">Privacy Policy</a>
                &middot;
                <a href="#">Terms &amp; Conditions</a>
            </div>
        </div>
    </div>
</footer>

resources/views/admin/partials/left_navbar.blade.php
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>
                <!---- Product Navigate ---->
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#product" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fab fa-product-hunt"></i></div>
                    Product
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="product" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{ route("admin.product.index") }}">Danh Sách</a>
                        <a class="nav-link" href="{{ route("admin.product_category.index") }}">Danh Mục</a>
                        <a class="nav-link" href="{{ route("admin.product_tags.index") }}">Tags</a>
                    </nav>
                </div>

                <!---- Blog Navigate ---->
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#blog" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fab fa-product-hunt"></i></div>
                    Blog
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="blog" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{ route("admin.blog.index") }}">Danh Sách</a>
                        <a class="nav-link" href="{{ route("admin.blog_category.index") }}">Danh Mục</a>
{{--                        <a class="nav-link" href="{{ route("admin.blog_tags.index") }}">Tags</a>--}}
                    </nav>
                </div>

                <!---- Setting Navigate ---->
                <a class="nav-link collapsed" href="{{ route('admin.setting.index') }}"  aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-cog"></i></div>
                    Setting
                </a>

                <!---- Coupon Navigate ---->
                <a class="nav-link collapsed" href="{{ route('admin.coupon.index') }}"  aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-percentage"></i></div>
                    Coupon
                </a>
                 {{-- ----------- Customer Menu ----------  --}}
                <a class="nav-link collapsed" href="{{ route('admin.customer.index') }}"  aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-percentage"></i></div>
                    Account Client
                </a>
                <!---- Bank Navigate ---->
                <a class="nav-link collapsed" href="{{ route('admin.bank.index') }}"  aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-university"></i></div>
                    Bank
                </a>
                <!---- Menu Navigate ---->
                <a class="nav-link collapsed" href="{{ route('admin.menu.index') }}"  aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-bars"></i></div>
                    Menu
                </a>


                <a class="nav-link collapsed" href="{{ route('admin.qa.index') }}"  aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-bars"></i></div>
                    Q&A
                </a>
                <!---- User Navigate ---->
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#users" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-user-secret"></i></div>
                    Users
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="users" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{ route("admin.user.index") }}">Danh sách User</a>
                        <a class="nav-link" href="{{ route("admin.role.index") }}">Danh sách Role</a>
                    </nav>
                </div>

                <!---- Widget Navigate ---->
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#widget" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-arrows-alt-h"></i></div>
                    Widget
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="widget" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{ route("admin.widget.index") }}">List Widget</a>
                        <a class="nav-link" href="{{ route("admin.partner.index") }}">Partners</a>
                        <a class="nav-link" href="{{ route("admin.banner.index") }}">Banners</a>
                    </nav>
                </div>

            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Logged in as:</div>
            @if(\Illuminate\Support\Facades\Auth::check())
                {{ \Illuminate\Support\Facades\Auth::user()->email }}
            @endif
        </div>
    </nav>
</div>

resources/views/admin/partials/top_navbar.blade.php
@php
    use Illuminate\Support\Facades\Auth;
    use App\Helper\Functions;
@endphp

<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ route("admin.user.index") }}">MY APP
        <span class="first-name">@if(Auth::check())({{ Auth::user() -> name }})@endif</span>
    </a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @if(Auth::check())
                    <img style="width: 35px; border-radius: 50%"
                         src="{{ Functions::getImage("user", Auth::user() -> picture) }}">
                    <span class="first-name">{{ Auth::user() -> name }}</span>
                @endif
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{{ route("authAdmin.logout") }}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<style>
    .first-name{
        font-size: 14px;
        opacity: .7;
    }
</style>